
http://localhost:3500/field_of_studies?page=1&limit=10
###################

POST http://localhost:3500/field_of_studies
content-type: application/json

{
    "name":"58مهندسی کامپیوتر"
}
###################

PUT http://localhost:3500/field_of_studies
content-type: application/json

{
    "id":6,
    "name":"مهندسی کامپیوتر شش"
}
###################

DELETE http://localhost:3500/field_of_studies
content-type: application/json

{
    "id":8
}
############################################################################
http://localhost:3500/users?page=1&limit=10
###################

http://localhost:3500/users/user
###################

POST http://localhost:3500/users
content-type: application/json

{ 
    "email":"ali@yahoo.com59",
    "password":"1234",
    "firstName":"a",
    "lastName":"b",
    "role":2,
    "field_of_study_id":1
}
###################

PUT http://localhost:3500/users
content-type: application/json

{ 
    "id":1,
    "email":"m_morteza_a@yahoo.com",
    "password":"a1",
    "firstName":"علی",
    "lastName":"لاله",
    "phoneNumber":"09163214895",
    "role": 2,
    "field_of_study_id": 42
}
###################

DELETE http://localhost:3500/users
content-type: application/json

{
    "id":55
}
############################################################################

POST http://localhost:3500/auth/login
content-type: application/json

{ 
    "email":"m_morteza_a@yahoo.com",
    "password":"3"
}
###################

http://localhost:3500/auth/logout

############################################################################

http://localhost:3500/messages/others?page=1&limit=10
###################

http://localhost:3500/messages/saved?page=1&limit=10
###################

http://localhost:3500/messages/sent?page=1&limit=10
###################

http://localhost:3500/messages/unseen-count
###################

POST http://localhost:3500/messages
content-type: application/json

{
    "title":"های",
    "body":"گود؟",
    "to_user_id":"sgm"
}
###################

PUT http://localhost:3500/messages
content-type: application/json

{
    "id":59,
    "title":"4با سلام",
    "body":"4کار را انجان دهید",
    "to_user_id":10
}
###################

DELETE http://localhost:3500/messages
content-type: application/json

{
    "id":1,
    "forBoth":true
}

############################################################################

http://localhost:3500/colleges?page=1&limit=10
###################

POST http://localhost:3500/colleges
content-type: application/json

{
    "name":"کامپیوتر59"
}
###################

PUT http://localhost:3500/colleges
content-type: application/json

{
    "id":6,
    "name":"کامپیوتر شش"
}
###################

DELETE http://localhost:3500/colleges
content-type: application/json

{
    "id":8
}
############################################################################

http://localhost:3500/times?page=1&limit=10
###################

POST http://localhost:3500/times
content-type: application/json

{
    "start":8,
    "end":11
}
###################

PUT http://localhost:3500/times
content-type: application/json

{
    "id":58,
    "start":"13",
    "end":"15"
}
###################

DELETE http://localhost:3500/times
content-type: application/json

{
    "id":56
}
############################################################################

http://localhost:3500/professors?page=1&limit=10
content-type: application/json

{ 
    "field_of_study_id":"all",
    "isInvited":"all",
    "lastGrade":"all"
}
###################

POST http://localhost:3500/professors
content-type: application/json

{ 
    "firstName":"a",
    "lastName":"b",
    "lastGrade":1,
    "isInvited":true,
    "email":"ali@yahoo.com60",
    "phoneNumber":"09125648796",
    "field_of_study_id":1
}
###################

PUT http://localhost:3500/professors
content-type: application/json

{ 
    "id":1,
    "firstName":"c",
    "lastName":"d",
    "lastGrade":2,
    "isInvited":true,
    "email":"ali@yahoo.com6000",
    "phoneNumber":"09125648733",
    "field_of_study_id":3
}
###################

DELETE http://localhost:3500/professors
content-type: application/json

{
    "id":59
}
############################################################################

http://localhost:3500/classes?page=1&limit=10
content-type: application/json

{ 
    "college_id":"all",
    "hasProjector":"all",
    "capacity":"all"
}
###################

POST http://localhost:3500/classes
content-type: application/json

{ 
    "title":"کارگاهی 3",
    "capacity":60,
    "hasProjector":false,
    "college_id":12
}
###################

PUT http://localhost:3500/classes
content-type: application/json

{ 
    "id":61,
    "title":"کارگاهی 4",
    "capacity":80,
    "hasProjector":true,
    "college_id":2
}
###################

DELETE http://localhost:3500/classes
content-type: application/json

{
    "id":61
}
############################################################################

http://localhost:3500/courses?page=1&limit=10
content-type: application/json

{ 
    "field_of_study_id":"all",
    "termNumber":"all",
    "kind":"all"
}
###################

POST http://localhost:3500/courses
content-type: application/json

{ 
    "name":"a",
    "code":"111222",
    "unit":2,
    "kind":"b",
    "grade":1,
    "termNumber":6,
    "prerequisite_id":3,
    "need_id":9,
    "field_of_study_id":10
}
###################

PUT http://localhost:3500/courses
content-type: application/json

{ 
    "id":59,
    "name":"b",
    "code":"333444",
    "unit":3,
    "kind":"c",
    "grade":2,
    "termNumber":8,
    "prerequisite_id":6,
    "need_id":10,
    "field_of_study_id":11
}
###################

DELETE http://localhost:3500/courses
content-type: application/json

{
    "id":59
}
############################################################################

http://localhost:3500/semesters?page=1&limit=10
content-type: application/json

{ 
    "hasTestDates":true
}
###################

POST http://localhost:3500/semesters
content-type: application/json

{ 
    "educationYear":1405,
    "yearPart":2,
    "semesterDate":"s_mon",
    "unitDate":"u_mon",
    "editUnitDate":"e_mon",
    "first":"1_mon",
    "second":"2_mon",
    "third":"3_mon",
    "fourth":"4_mon",
    "fifth":"5_mon",
    "sixth":"6_mon",
    "seventh":"7_mon",
    "eighth":"8_mon",
    "ninth":"9_mon",
    "tenth":"10_mon",
    "eleventh":"11_mon",
    "twelfth":"12_mon",
    "thirteenth":"13_mon",
    "fourteenth":"14_mon",
    "message_title":"با سلام شروع همگانی",
    "message_body":"کار همگانی را آغاز کنید"
}
###################

PUT http://localhost:3500/semesters
content-type: application/json

{ 
    "id":59,
    "test_date_id":59,
    "educationYear":1406,
    "yearPart":3,
    "semesterDate":"s_monday",
    "unitDate":"u_monday",
    "editUnitDate":"e_monday",
    "first":"1_monday",
    "second":"2_monday",
    "third":"3_monday",
    "fourth":"4_monday",
    "fifth":"5_monday",
    "sixth":"6_monday",
    "seventh":"7_monday",
    "eighth":"8_monday",
    "ninth":"9_monday",
    "tenth":"10_monday",
    "eleventh":"11_monday",
    "twelfth":"12_monday",
    "thirteenth":"13_monday",
    "fourteenth":"14_monday"
}
###################

DELETE http://localhost:3500/semesters
content-type: application/json

{
    "id":12,
    "test_date_id":12
}
############################################################################
http://localhost:3500/schedules
content-type: application/json

###################
http://localhost:3500/schedules/weekly?field_of_study_id=all&professor_id=all&termNumber=all&class_id=all&semester_id=64
content-type: application/json

###################
http://localhost:3500/schedules/test?field_of_study_id=all&professor_id=all&termNumber=all&semester_id=64
content-type: application/json

###################
http://localhost:3500/schedules/schedule?id=9
content-type: application/json

###################

http://localhost:3500/schedules/class-schedules?class_id=45
content-type: application/json

###################

POST http://localhost:3500/schedules
content-type: application/json

{
    "testDay":10,
    "testDayPart":9,
    "maxCapacity":30,
    "minCapacity":10,
    "courseGroup":6,
    "semester_id":45,
    "course_id":29,
    "professor_id":45,
    "host_field_of_study_id":-1,
    "accessibleFor_user_id":12,
    "class1_id":19,
    "weekDay1":1,
    "weekKindClass1":3,
    "time1_id":4,
    "class2_id":56,
    "weekDay2":5,
    "weekKindClass2":1,
    "time2_id":51
}
###################

POST http://localhost:3500/schedules/weekly-email
content-type: application/json

{
    "professor_id":11,
    "semester_id":52
}
###################

POST http://localhost:3500/schedules/test-email
content-type: application/json

{
    "professor_id":11,
    "semester_id":52
}
###################
PUT http://localhost:3500/schedules
content-type: application/json

{ 
    "id":70,
    "testDay":10,
    "testDayPart":9,
    "maxCapacity":30,
    "minCapacity":10,
    "courseGroup":6,
    "semester_id":8,
    "course_id":29,
    "professor_id":9,
    "host_field_of_study_id":8,
    "accessibleFor_user_id":12,
    "class1_id":10,
    "weekDay1":6,
    "weekKindClass1":3,
    "time1_id":14,
    "class2_id":-1,
    "weekDay2":-1,
    "weekKindClass2":-1,
    "time2_id":-1
}
###################

PUT http://localhost:3500/schedules/change-state
content-type: application/json

{ 
    "id":1
}
###################

DELETE http://localhost:3500/schedules
content-type: application/json

{
    "id":2
}